# Generated by Django 2.2 on 2020-01-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('situation', models.TextField(null=True)),
                ('details', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
