# Generated by Django 2.2.6 on 2020-01-07 12:40

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=200)),
                ('situation', models.TextField()),
                ('details', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=builtins.id)),
            ],
        ),
    ]
