# Generated by Django 2.2.6 on 2020-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
