# Generated by Django 2.2 on 2020-01-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200107_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
