# Generated by Django 2.2 on 2020-01-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200107_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
